services:
  backend:
    build:
      context: .
    env_file:
      - .env
    container_name: backend_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:rootpass2025@db:5432/mtg_teste?schema=public
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_network

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpass2025
      POSTGRES_DB: mtg_teste
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d mtg_teste']
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
